<?xml version="1.0" encoding="UTF-8"?>
<!--Published by JAX-WS RI at http://jax-ws.dev.java.net. RI's version is Oracle JAX-WS 2.1.5.--><xs:schema version="1.0" targetNamespace="http://osbcorp.vtr.cl/REC/EMP/ConsultarSaldoFavor/" xmlns:tns="http://osbcorp.vtr.cl/REC/EMP/ConsultarSaldoFavor/" xmlns:ns3="http://osbcorp.vtr.cl/GLOBAL/EMP/HeaderResponse" xmlns:ns2="http://osbcorp.vtr.cl/GLOBAL/EMP/HeaderRequest" xmlns:ns1="http://osbcorp.vtr.cl/REC/EMP/ConsultarSaldoFavor" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import namespace="http://osbcorp.vtr.cl/REC/EMP/ConsultarSaldoFavor" schemaLocation="ConsultaDevolucionSAFService_1.xsd"/>
  <xs:import namespace="http://osbcorp.vtr.cl/GLOBAL/EMP/HeaderRequest" schemaLocation="ConsultaDevolucionSAFService_3.xsd"/>
  <xs:import namespace="http://osbcorp.vtr.cl/GLOBAL/EMP/HeaderResponse" schemaLocation="ConsultaDevolucionSAFService_4.xsd"/>
  <xs:element name="consultarSaldoFavor" type="tns:consultarSaldoFavor"/>
  <xs:element name="consultarSaldoFavorResponse" type="tns:consultarSaldoFavorResponse"/>
  <xs:complexType name="consultarSaldoFavor">
    <xs:sequence>
      <xs:element name="arg0" type="ns1:ConsultaSaldoFavorPeticionType" minOccurs="0"/>
      <xs:element name="arg1" type="ns2:HeaderRequest" minOccurs="0"/>
      <xs:element name="arg2" type="ns1:ConsultaSaldoFavorRespuestaType" minOccurs="0"/>
      <xs:element name="arg3" type="ns3:datosHeaderResponse" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="consultarSaldoFavorResponse">
    <xs:sequence>
      <xs:element name="arg2" type="ns1:ConsultaSaldoFavorRespuestaType" minOccurs="0"/>
      <xs:element name="arg3" type="ns3:datosHeaderResponse" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>