# 
# LEVEL=<DEBUG | INFO | WARN | ERROR | FATAL>
# APPENDER=<USER DEFINED>
#
# Root logger (must be): LEVEL, APPENDER_1, APPENDER_2, ...
log4j.rootLogger=INFO, stdout

# Logger de Cajas: LEVEL, APPENDER_1, APPENDER_2, ...
# Vista
log4j.logger.visor=INFO, vista, stdout
# Cajas Basica
# log4j.logger.cajasCTC=DEBUG, cajasCTC, stdout
log4j.logger.cajasClaro=DEBUG, cajasClaro, stdout
# SwitchClient
log4j.logger.SwitchClient=INFO, switch, stdout

# stdout es ConsoleAppender.
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern= [%d] (%F:%L) [%-5p] %m%n

# ppal es RollingFileAppender
log4j.appender.vista=org.apache.log4j.RollingFileAppender
#log4j.appender.vista.File=/RedDePagos/logs/vistaCTC.log
log4j.appender.vista.File=/RedDePagos/logs/vistaClaro.log
log4j.appender.vista.MaxFileSize=10MB
log4j.appender.vista.MaxBackupIndex=10
log4j.appender.vista.layout=org.apache.log4j.PatternLayout
log4j.appender.vista.layout.ConversionPattern= [%d] [%-5p] %m%n


# DEVICE_POS se setea como RollingFileAppender
log4j.appender.cajasClaro=org.apache.log4j.RollingFileAppender
#log4j.appender.cajasCTC.File=/RedDePagos/logs/cajasCTC.log
log4j.appender.cajasClaro.File=/RedDePagos/logs/cajasClaro.log
log4j.appender.cajasClaro.MaxFileSize=4096KB
log4j.appender.cajasClaro.MaxBackupIndex=10
log4j.appender.cajasClaro.layout=org.apache.log4j.PatternLayout
log4j.appender.cajasClaro.layout.ConversionPattern=[E:%d] (%F:%L) [%-5p]  %m%n

# DEVICE_POS se setea como RollingFileAppender
log4j.appender.switch=org.apache.log4j.RollingFileAppender
#log4j.appender.switch.File=/RedDePagos/logs/switchCTC.log
log4j.appender.switch.File=/RedDePagos/logs/switchClaro.log
log4j.appender.switch.MaxFileSize=4096KB
log4j.appender.switch.MaxBackupIndex=10
log4j.appender.switch.layout=org.apache.log4j.PatternLayout
log4j.appender.switch.layout.ConversionPattern=[E:%d] (%F:%L) [%-5p]  %m%n
