# properties.cfg (iso8859-1)

singleInstanceLockFile=rpcajas.lock
log4jConfig=config/log4j.properties
log4jLoggerClass=visor

trxFile=config/partitura.xml
starterTrx=login
configTrx=configura

splashBgColor=0xFFFFFF
#splashFgColor=0xFF0000
splashFgColor=0xE40808
splashLabel1=Claro: Sistema de Cajas v 2.0.2 (Move/5000)
splashLabel2=Inicializando aplicación...

mainTopBgColor=0xFFFFFF
#mainTopFgColor=0xFF0000
mainTopFgColor=0xE40808
mainTopTitle=Claro: Sistema de Cajas
mainIcon=config/logo.png

mainCenterCartBgColor=0xE40808
mainCenterCartFgColor=0xFFFFFF

mainCenterButtonsBgColor=0xE40808
mainCenterButtonsFgColor=0xFFFFFF
# ORDEN DE LOS BOTONES: 'column' o 'row'
buttonOrder=column

mainBottomBgColor=0xFFFFFF
#mainBottomFgColor=0xFF0000
mainBottomFgColor=0xE40808
#mainBottomFgMsgColor=0xFF0000
mainBottomFgMsgColor=0xE40808

starterTrxOffLine=loginOffLine

reportLogo=config/logo-doc.jpg